### ISSUE TITLE
Insert last empty line

### ISSUE THREAD

**Issue by cirelli94** [minherz/copyright-inserter#7] opened 2021-04-30 15:15 UTC
I'm using this extension with setting `copyrightInserter.useLineComment` set as `false`, this time :) .
I don't like that it doesn't add last empty line at the bottom of the copyright, e.g.:
```
...
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package marshal

...
```
But I'd like it to be:
```
...
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package marshal

...
```

Would you mind if I open a PR for this?
Or would be this an option in settings maybe?

Here the patch:
```
diff --git a/src/copyrightinserter.ts b/src/copyrightinserter.ts
index eb21060..fe72347 100644
--- a/src/copyrightinserter.ts
+++ b/src/copyrightinserter.ts
@@ -240,7 +240,11 @@ along with this program.  If not, see <https://www.gnu.org/licenses/>.`]
             const new_line = prefix + line;
             result += new_line.trimRight() + "\n";
         }
-        return result += last_line + "\n";
+        if (last_line !== "") {
+            result += last_line + "\n";
+        }
+
+        return result += "\n";
     }
 
     private formatHeader(template: (holder: string, year: string) => string, data: CopyrightData, language: vscode.LanguageConfiguration, useLineComment: boolean): string {

```

Thanks in advance

**Comment by minherz** [comment] 2021-07-24 08:19
Duplicate of #10

**Closed as completed by minherz** 2021-07-24 08:19 UTC
