### ISSUE TITLE
[BUG]: not working in .vue files

### ISSUE THREAD

**Issue by evil-shrike** [minherz/copyright-inserter#24] opened 2024-01-25 11:06 UTC
### Plugin Version

1.0.14

### What happened?

being in a vue files pressed shift-cmd-p, executed 'copywrite: insert header',
got an error:
Command 'Copyright: Insert Header' resulted in an error. 
The "path" argument must be of type string. Received undefined. 

### What did you expect to happened?

a header is inserted

### Relevant log output

```shell
2024-01-25 15:04:32.040 [error] TypeError: The "path" argument must be of type string. Received undefined
	at new NodeError (node:internal/errors:399:5)
	at validateString (node:internal/validators:163:11)
	at Object.join (node:path:1166:7)
	at CopyrightInserter.getLanguageConfigById (/Users/segy/.vscode/extensions/minherz.copyright-inserter-1.0.14/out/copyrightinserter.js:167:71)
	at CopyrightInserter.insertHeader (/Users/segy/.vscode/extensions/minherz.copyright-inserter-1.0.14/out/copyrightinserter.js:117:29)
	at insertHeader (/Users/segy/.vscode/extensions/minherz.copyright-inserter-1.0.14/out/extension.js:33:9)
	at d.h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:141:140094)
	at d.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:141:140954)
	at l.S (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:10829)
	at l.Q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:10595)
	at l.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:9685)
	at l.L (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:8764)
	at f.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:7567)
	at n.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at o.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:103:14039)
	at f.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:7903)
	at n.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at o.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:103:14039)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:6183)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367) copyright.insertHeader {"value":"minherz.copyright-inserter","_lower":"minherz.copyright-inserter"}
```

**Comment by minherz** [comment] 2024-01-27 20:41
Hello @evil-shrike , I've made a quick check and I didn't find support for the SFC Syntax in the language configurations that come with VS Code. As you can see in the [description] the extension uses information stored in the language configuration of the current file to discover the comment syntax. Because it does not find language configuration (the `.vue` files are handled by the VSCode as "Plaint Text") it does not process. While it is possible to "just insert" the copyright text without using the proper comment syntax if the language is not detected, it does not look to me as the right solution.

Since the description of the issue does not mention if you have the custom language configuration installed into your instance of the VS Code. I close this issue with "Won't fix" remark. If you do use the language confguration (i.e. the right bottom area in the status bar of the VS Code shows the language configuration name and not "Plain Text"), please add instructions for installing this language configuration and I will try to reproduce and then fix the problem.

**Comment by evil-shrike** [comment] 2024-01-29 08:59
Hi @minherz.
Well, even for plain text I believe showing the error 'TypeError: The "path" argument must be of type string' isn't correct behavior. Why not to show a warning 'format not support' or smth like that. But honestly inserting the copyright text as is doesn't seem as a bad idea as well.

But. Vue files aren't plain text:
<img width="1495" alt="image" src="https://github.com/minherz/copyright-inserter/assets/1203230/a9b9eac0-4780-4c0d-80bf-3f8e668275cc">

I have Volar installed
https://marketplace.visualstudio.com/items?itemName=Vue.volar

**Comment by minherz** [comment] 2024-01-31 04:33
@evil-shrike thank you for the constructive feedback. I will look to change the error message to be more informative. I will also look to install the extension and see why the [language configuration][1] it is supposed to install isn't recognized.

I will consider supporting inserting the copyright as a plaint text. I am not familiar with the use cases when it has the value. In this particular case it is more a hack than a solution. However, it is possible to enable it as a behavior in the event a language configuration isn't found.

I cannot promise a quick resolution but I will do my best to address this issue during February. Apologies for potential inconvenience.

[1]: https://github.com/vuejs/language-tools/blob/f3de42803c7b3a8f5536eaed02e133c093d51f90/extensions/vscode/languages/vue-language-configuration.json

**Comment by minherz** [comment] 2024-02-03 20:42
I checked the behavior of the extension with the latest version of the Volar installed. It works as expected. I wasn't able to reproduce the error that you show in the description.

The reproducing sequence I used was as below:

1. Install the "Vue Language Features (Volar)" extension with the latest version (v1.8.27).
2. Create a new value vue file and give it `.vue` extension. (see the content of the file that I used in the next paragraph)
3. Open the file in VS Code
4. Insert the copyright header by pressing `Ctrl-Shift-P` and selecting "Copyright: Insert header"

I used a simple vue file content:

```
<!--
Say Hello World with Vue!
-->

<script setup>
import { ref } from 'vue'

// A "ref" is a reactive data source that stores a value.
// Technically, we don't need to wrap the string with ref()
// in order to display it, but we will see in the next
// example why it is needed if we ever intend to change
// the value.
const message = ref('Hello World!')
</script>

<template>
  <h1>{{ message }}</h1>
</template>
```

The header was inserted above the "Say Hello..." comment.

I will fix the error generated by the extension when it fails to find the language. However, the specific use case that is reported in this issue cannot be reproduced. But I close this issue as non reproducible. If you have clarification regarding the reproducing steps, feel free to reopen the issue.

**Closed as not planned by minherz** 2024-02-03 20:42 UTC
Labels: bug, wontfix
